[application]

[web.app]

# HTML title tag content
title = "dx_rs"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []


[bundle]
identifier = "Oscar Aspelin"
publisher = "Oscar Aspelin"
copyright = "Copyright 2025"
short_description = "Fullstack Rust Application"
long_description = "Fullstack Rust Application"
icon = ["assets/icon/16x16.png", "assets/icon/512x512.png"]